version: '3.1'
services:
  frontend-prod:
    container_name: nodeapp-prod
    build:
      context: .
      dockerfile: ./docker-frontend
    depends_on:
      - backend-prod
    command: npm run start
    volumes:
      - ./app:/app/
      - /app/node_modules
  backend-prod:
    image : mongo
    container_name: mongodb-prod
    env_file: .env
    command: 
      - --storageEngine
      - wiredTiger
      - --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - /opt/mongodb/node-cicd-docker/prod/:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
