version: '3.1'
services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/etc/ssl/nginx-reverse/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - /etc/ssl/etc/ssl/nginx-reverse/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    ports:
      - "80:80"
      - "443:443"

  frontend:
    container_name: nodeapp-prod
    build:
      context: .
      dockerfile: ./docker-frontend
    depends_on:
      - backend
    command: npm run start
    volumes:
      - ./app:/app/
      - /app/node_modules
  backend:
    image : mongo
    container_name: mongodb-prod
    env_file: .env
    command: 
      - --storageEngine
      - wiredTiger
      - --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - /opt/mongodb/:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
