name: sample
env:
  SUDO_PASS: ${{ secrets.SUDOPASS }}
  DB_PASS: ${{ secrets.DB_PASSWD }}
  DB_USER: ${{ secrets.DB_USERNAME }}
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Compose app with docker
      run: |
        export DB_PASS="$DB_PASS"
        export DB_USER="$DB_USER"
        echo "$SUDO_PASS" | sudo -S docker-compose -f /opt/projects/node-cicd-docker/node-cicd-docker/app-compose.yml up --detach
