name: sample
env:
  sudo_pass: ${{ secrets.SUDOPASS }}
  db_pass: ${{ secrets.DB_PASSWD }}
  db_user: ${{ secrets.DB_USERNAME }}
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Compose app with docker
      run: |
        export DB_PASS="$db_pass"
        export DB_USER="$db_user"
        echo $DB_PASS
        # echo "$sudo_pass" | sudo -S docker-compose -f /opt/projects/node-cicd-docker/node-cicd-docker/app-compose.yml up --detach
