name: sample
env:
  sudopass: ${{ secrets.SUDOPASS }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Sudo Compose
      run: | 
        echo "$sudopass" | sudo -S docker-compose -f /opt/project/node-cicd-docker/node-cicd-docker/node-compose.yml up --detach
