name: sample

on:
  workflow_dispatch:

jobs:
  build:

    runs-on:
      - self-hosted
      - label-1
    steps:
      - uses: actions/checkout@v2
      - name: Run one-line script
        run: |
          echo Hello World!
          sleep 15
          Bye!
