name: sample
env:
  sudopass: ${{ secrets.SUDOPASS }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Sudo Test
      run: | 
        echo "$sudopass" | sudo -S id
